export const EditingMark = '->'
export const AdditionMark = '+++'
export const RemovalMark = '---'
export const EditingBackgroundColor = '#ddf4ff'
export const AdditionBackgroundColor = '#e6ffec'
export const RemovalBackgroundColor = '#ffebe9'
